#!/data/data/com.termux/files/usr/bin/sh
# Menu Item
URL=$1

menu()
{
MPX=$(termux-dialog radio -v "Descargar MP3,Descargar video (mejor versión),Descargar video (max 480p),Mostrar formatos,Salir" -t "Descargar como... (por defecto, MP3)" | jq -r .index)
case "$MPX" in

                0) amp3;;
                1) avideo;;
                2) avideopeque;;
                3) formatos;;
                4) exit 0;;
             null) exit 0;;

                *)  ;;
        esac
}



amp3()
{
    youtube-dl --no-mtime --extract-audio --audio-format mp3 --audio-quality 0 --add-metadata $URL
    termux-toast "MP3 descargado"
    exit 0
}

avideo()
{
	youtube-dl --no-mtime -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best' --add-metadata $URL
	termux-toast "Video descargado"
        exit 0
}

avideopeque()
{
    youtube-dl --no-mtime -f "best[height<=720]" --add-metadata $URL
    termux-toast "Video descargado"
    exit 0
}

formatos()
{
    youtube-dl -F $URL | sed -n '/format code/,$p'| sed -n '/webm/!p' | awk '{print $1,"\011",$2,"\011",$3}'
    echo Introduce el formato. Puede ser XXX+YYY:
    read varname
    youtube-dl --no-mtime -f $varname --add-metadata $URL
    exit 0
}

menu

